<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_06" Id="{6ecf139c-2195-4a29-8a30-43f96ef9e2d8}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_06
VAR_INPUT
	Tuyen AT %I* : BOOL;
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>