<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_06" Id="{69625126-d6e4-454f-ac97-83b83af6b66f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_06
VAR_INPUT
	Trong AT %I* : BOOL;
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>